# Generated by Django 4.1.7 on 2023-03-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_item', models.CharField(default='Заголовок фрагмента', max_length=255, verbose_name='Заголовок фрагмента')),
                ('nav_item', models.CharField(default='Фрагмент в навигации', max_length=255, verbose_name='Фрагмент в навигации')),
                ('nav_position', models.IntegerField(default=0, verbose_name='Приоритет в навигации')),
                ('content', models.TextField(default='Основное содержание фрагмента', max_length=255, verbose_name='Основное содержание фрагмента')),
                ('current_date', models.DateTimeField(auto_now=True, verbose_name='Дата Записи')),
            ],
            options={
                'verbose_name': 'Содержание фрагмента',
                'verbose_name_plural': 'Содержание фрагментов',
                'ordering': ('-nav_item',),
            },
        ),
    ]
