# Generated by Django 4.1.7 on 2023-03-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(default='Основное содержание фрагмента', verbose_name='Основное содержание фрагмента'),
        ),
    ]
