# Generated by Django 4.1.7 on 2023-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=models.TextField(default='<h6 class="card-subtitle mb-2 text-body-secondary "> <a id="h1">Раздел 1</a></h6><p class="card-text">Содержание раздела 1</p><a href="#h1" class="card-link">На раздел 1</a>', verbose_name='Основное содержание фрагмента'),
        ),
    ]
