# Generated by Django 4.1.7 on 2023-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_nav',
            field=models.CharField(default='Фрагмент в навигации', max_length=255, verbose_name='Фрагмент в навигации '),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_nav_position',
            field=models.IntegerField(default=0, verbose_name='Приоритет в навигации (0 - исключить)'),
        ),
    ]
