# Generated by Django 4.1.7 on 2023-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_alter_item_item_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_content',
            field=models.TextField(default='<a id="top_of _page" href="#h1" class="card-link">На раздел 1</a><h6 class="card-subtitle mb-2 text-body-secondary "><a id="h1">Раздел 1</a></h6><p class="card-text">Содержание раздела 1</p><img src="/static/images/settings_django.png"  height="30px"><a href="#top_of _page" class="card-link">к началу страницы</a>', verbose_name='Основное содержание страницы'),
        ),
    ]
