# Generated by Django 4.1.7 on 2024-04-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0015_alter_item_item_nav_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_nav_position',), 'verbose_name': 'Содержание текущей страниы', 'verbose_name_plural': 'Содержание всех страниц'},
        ),
    ]
