# Generated by Django 4.1.7 on 2024-05-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0016_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_nav_position',), 'verbose_name': 'Содержание текущей страницы', 'verbose_name_plural': 'Содержание всех страниц'},
        ),
        migrations.AlterField(
            model_name='item',
            name='item_nav_position',
            field=models.IntegerField(default=1, help_text='большее - число правее, 0 - исключить из навигации', verbose_name='Приоритет ссылки в навигации (0 - исключить)'),
        ),
    ]
